#!/usr/bin/env bash


prefix="package_$2"

if [[ "_elasticsearch_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _elasticsearch_volume
	fi
	
if [[ "_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _grafana_volume
	fi
	
