#!/usr/bin/env bash


prefix="package_$2"


executionplane --silent docker container prune --force

if [[ "_elasticsearch_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "_elasticsearch_volume"
			result=$(docker volume ls | grep "_elasticsearch_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "_grafana_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "_grafana_volume"
			result=$(docker volume ls | grep "_grafana_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
