#!/usr/bin/env bash


prefix="package_$2"

if [[ "package_ekg_elasticsearch_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ekg_elasticsearch_volume
	fi
	
if [[ "package_ekg_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ekg_grafana_volume
	fi
	
