#!/usr/bin/env bash


prefix="package_$2"


executionplane --silent docker container prune --force

if [[ "package_ekg_elasticsearch_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume rm --force package_ekg_elasticsearch_volume
	fi
	
if [[ "package_ekg_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume rm --force package_ekg_grafana_volume
	fi
	
